apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipe-thumbnail
spec:
  replicas: {{ .Values.kerberospipeline.thumbnail.replicas }}
  selector:
    matchLabels:
      app: pipe-thumbnail
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pipe-thumbnail
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: pipe-thumbnail
        image: "{{ .Values.kerberospipeline.thumbnail.repository }}:{{ .Values.kerberospipeline.thumbnail.tag }}"
        imagePullPolicy: {{ .Values.kerberospipeline.thumbnail.pullPolicy }}
        resources:
          requests:
            memory: 10Mi
            cpu: 10m
        env:
        - name: CLOUD_PROVIDER
          value: "{{ .Values.cloudProvider }}"
        - name: QUEUE_SYSTEM
          value: "{{ .Values.queueProvider }}"

        # Kafka settings
        - name: KAFKA_BROKER
          value: "{{ .Values.kafka.broker }}"
        - name: KAFKA_USERNAME
          value: "{{ .Values.kafka.username }}"
        - name: KAFKA_PASSWORD
          value: "{{ .Values.kafka.password }}"
        - name: KAFKA_MECHANISM
          value: "{{ .Values.kafka.mechanism }}"
        - name: KAFKA_SECURITY
          value: "{{ .Values.kafka.security }}"

        # Thumbnail generation
        - name: THUMBNAIL_QUALITY
          value: "{{ .Values.kerberospipeline.thumbnail.quality }}"
        - name: THUMBNAIL_WIDTH
          value: "{{ .Values.kerberospipeline.thumbnail.width }}"
        - name: THUMBNAIL_HEIGHT
          value: "{{ .Values.kerberospipeline.thumbnail.height }}"

        # There is an option to store the thumbnails in a storage provider in Kerberos Vault.
        # This will lower storage in mongodb.
        - name: THUMBNAIL_VAULT_ENABLED
          value: "{{ .Values.kerberospipeline.thumbnail.kerberosvault.enabled }}"
        - name: VAULT_THUMBNAIL_PROVIDER
          value: "{{ .Values.kerberosvault.thumbnail.provider }}"
        - name: VAULT_THUMBNAIL_ACCESS_KEY
          value: "{{ .Values.kerberosvault.thumbnail.accessKey }}"
        - name: VAULT_THUMBNAIL_SECRET_KEY
          value: "{{ .Values.kerberosvault.thumbnail.secretKey }}"